main: org.hcsoups.hardcore.Hardcore
name: ${project.name}
version: ${project.version}
website: ${project.url}
authors: ["§crbrick"]

permissions:
  warps.#:
    description: warp.<Number of warps>
  spawn.build:
    default: op